name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build the First Docker Image
      run: docker build -t api-feed ./api-feed --tag rilhomie/api-feed:v1
    - name: Docker Push
      run: docker push rilhomie/api-feed:v1
      
    - name: Build the Second Docker Image
      run: docker build -t api-user ./api-user --tag rilhomie/api-user:v1
    - name: Docker Push
      run: docker push rilhomie/api-user:v1
      
    - name: Build the Third Docker Image
      run: docker build -t udagram-frontend ./frontend --tag rilhomie/udagram-frontend:v1
    - name: Docker Push
      run: docker push rilhomie/udagram-frontend:v1
      
    - name: Build the Proxy Server Docker Image
      run: docker build -t udagram-proxyserver ./proxyserver --tag rilhomie/udagram-proxyserver:v1
    - name: Docker Push
      run: docker push rilhomie/udagram-proxyserver:v1
      
      
